import Head from 'next/head';
import styles from './styles.module.scss';

import Header from '../components/Header';
import Search from '../components/Search';
import List from '../components/List';

export default function Home({ titles }) {
  return (
    <div className={styles.main}>
      <Head>
        <title>Star Wars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/head.png" />
      </Head>

      <Header />
      <Search placeholder={'Enter a Film Title...'} data={titles} />
      <List results={titles} />
    </div>
  );
}

// This function gets called at build time
export async function getStaticProps() {
  const res = await fetch('https://www.swapi.tech/api/films');
  const titles = await res.json();

  return {
    props: {
      titles,
    },
  };
}
