import Head from 'next/head';
import styles from '../styles/Home.module.scss';

import Header from '../components/Header';
import Search from '../components/Search';
import List from '../components/List';

export default function Home({ results }) {
  //console.log(results);
  return (
    <div className={styles.main}>
      <Head>
        <title>Star Wars</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/head.png" />
      </Head>

      <Header />
      <Search placeholder={'Enter a Film Name'} data={results} />
      <List results={results} />
    </div>
  );
}

export async function getServerSideProps() {
  const request = await fetch('https://www.swapi.tech/api/films')
    .then((res) => res.json())
    .catch((err) => console.error(err));

  //console.log(request.result);
  return {
    props: {
      results: request.result,
    },
  };
}
